Add: homepage and navbar pages and components
keironchaudhry/bookshop-project pull request #20
Opened 2023-11-15 14:12 UTC by JodyMurray

Create:  - Home.tsx file (pages)
              - Navbar.tsx file (components)
        
Add: bootstrap styling for navbar

2023-11-15 14:49 UTC, keironchaudhry requested changes
Looks all good except the changes in the main.tsx file - left a comment down there, let me know

2023-11-15 14:49 UTC, keironchaudhry commented on src/main.tsx
How come you removed the BrowserRouter from this file? Is it not needed? I've generally always put it here but let me know if that's unnecessary.

2023-11-15 15:12 UTC, JodyMurray commented on src/main.tsx
The app wouldn't function with more than one router in the app, got rid of it to test my components were working, need to find a way around it.

2023-11-16 07:55 UTC, keironchaudhry approved these changes

2023-11-16 07:55 UTC, merged